name: Deploy Python Bot
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Bot
        run: python main.py
        env:
          TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
